Repository vegaprotocol/vega-market-sim, pull requests merged in 2022-11, with the labels that each got.

#239 feat: update liquidity offset calculations
  vega_sim/scenario/common/agents.py
Labels: bug

#235 feat: implement batch-market-instructions
  vega_sim/api/data.py
  vega_sim/api/data_raw.py
  vega_sim/api/trading.py
  vega_sim/scenario/common/agents.py
  vega_sim/service.py
Labels: enhancement

#242 feat: network_service upgrades
  vega_sim/environment/environment.py
  vega_sim/network_service.py
  vega_sim/scenario/adhoc.py
  vega_sim/scenario/common/agents.py
  vega_sim/scenario/common/utils/price_process.py
  vega_sim/scenario/configurable_market/agents.py
  vega_sim/scenario/constants.py
  vega_sim/scenario/fairground/scenario.py
  vega_sim/scenario/network/scenario.py
Labels: bug, enhancement

#243 feat: network error handling
  vega_sim/api/data.py
  vega_sim/environment/environment.py
  vega_sim/network_service.py
  vega_sim/service.py
Labels: enhancement

#245 feat: add devops dir
  .env
  devops/README.md
  devops/classes.py
  devops/registry.py
  devops/run.py
  devops/scenario.py
  devops/wallet.py
Labels: documentation, enhancement

#246 feat: default price process fn
  tests/integration/test_parameter_runner.py
  vega_sim/scenario/common/utils/price_process.py
  vega_sim/scenario/comprehensive_market/scenario.py
  vega_sim/scenario/configurable_market/scenario.py
  vega_sim/scenario/curve_market_maker/scenario.py
  vega_sim/scenario/fairground/agents.py
  vega_sim/scenario/fairground/scenario.py
  vega_sim/scenario/ideal_market_maker/scenario.py
  vega_sim/scenario/ideal_market_maker/utils/price_process.py
  vega_sim/scenario/ideal_market_maker_v2/scenario.py
  vega_sim/scenario/ideal_market_maker_v2/utils/price_process.py
  vega_sim/scenario/market_crash/scenario.py
  vega_sim/scenario/multi_market/scenario.py
  vega_sim/scenario/network/scenario.py
  vega_sim/scenario/registry.py
Labels: enhancement

#251 fix: correct random_walk logic
  vega_sim/scenario/common/utils/price_process.py
Labels: bug

#254 feat: tidy-up and rerun network parameter test
  parameter_results/MIN_LP_STAKE_QUANTUM_DEMO/DemoNotebook.ipynb
  parameter_results/Siska_Curve/StakeToCcySiskas_Demo.ipynb
  parameter_results/StakeTargetScaling/NetworkParameter_NBC_StakeTargetScaling.ipynb
  parameter_results/StakeTargetScaling_v2/NetworkParameter_NBC_StakeTargetScaling.ipynb
  parameter_results/TargetStakeScaling_Curve/TargetStakeScaling_Demo.ipynb
  parameter_results/TauScaling/NetworkParameter_NBC_TauScaling.ipynb
  parameter_results/TauScaling_Curve/NetworkParameter_NBC_TauScaling_Curve.ipynb
  parameter_results/TauScaling_Curve/TauScaling_Demo.ipynb
  parameter_results/TauScaling_v2/NetworkParameter_NBC_TauScaling.ipynb
Labels: enhancement

#255 feat: CurvedMarketMaker order scaling
  .env
  devops/scenario.py
  tests/vega_sim/api/test_data.py
  tests/vega_sim/quant/__init__.py
  tests/vega_sim/quant/test_quant.py
  vega_sim/api/data.py
  vega_sim/environment/agent.py
  vega_sim/quant/__init__.py
  vega_sim/quant/quant.py
  vega_sim/scenario/common/agents.py
  vega_sim/scenario/configurable_market/agents.py
  vega_sim/scenario/configurable_market/scenario.py
  vega_sim/scenario/curve_market_maker/scenario.py
  vega_sim/scenario/multi_market/scenario.py
  vega_sim/service.py
Labels: enhancement

#261 fix: devops fixes
  vega_sim/scenario/configurable_market/agents.py
  vega_sim/scenario/constants.py
Labels: bug

#262 fix: revert torch to 1.12.1
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: bug

#260 feat: add one_off_transfers method
  tests/integration/test_trading.py
  vega_sim/api/trading.py
  vega_sim/service.py
  vega_sim/vegahome/genesis.json
Labels: enhancement
